yatube/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('', views.index, name="main_page"),
    path('groups/<slug:slug>/', views.group_posts, name="groups_list"),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace="posts")),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.TextField()
    slug = models.CharField(max_length=64)
    description = models.CharField(max_length=400)

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts')

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post, Group
# Create your views here.


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        "posts": posts,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    description = group.description
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'description': description,
        'posts': posts,
    }
    return render(request, template, context)

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    {% load static %}
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block title %}
    <title>Последние обновления на сайте</title>
    {% endblock  %}    
  </head>
  <body>
    {% include 'includes\header.html'%}
    {% block content %}
    <main> 
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">   
        {% block group_name %}  
        <h1>Последние обновления на сайте</h1>
        {% endblock %}
        {% block description %}
        <p> Default описание, чувачок </p>
        {% endblock  %}
        {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date | date:"d E Y" }}
          </li>
        </ul>
          <p> {{ post.text }} </p>
          {% if post.group %}
          <a href = "{% url 'posts:groups_list' post.group.slug %}"> все записи группы </a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        <!-- под последним постом нет линии -->
      </div>  
    </main>
    {% endblock  %}
    {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
<!-- Использованы классы бустрапа: -->
<!-- border-top: создаёт тонкую линию сверху блока -->
<!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
<!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
<footer class="border-top text-center py-3">
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
  <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
<header>
  {% load static %}
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:main_page' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Ya</span>tube
        </a>
      </div>
    </nav>      
</header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
<title>{{ title }}</title>
{% endblock  %}
{% block group_name %}
<h1>{{ group }}</h1>
{% endblock  %}
{% block description %}
<p> {{ description }} </p>
{% endblock  %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
<title>{{ title }}</title>
{% endblock  %}